### ISSUE TITLE
Design "flaw" on loading screen

### ISSUE THREAD

**Issue by Teconia** [crwntec/db-live-monitor#2]
Hey @crwntec ,
i know that this repo is currently WIP, but i found a minor design flaw and I think it should be a quick fix.
Your progress bar is not quite centered on my screen. I don't know if you used a fixed position for it.
Here the Screenshot:
![image](https://github.com/crwntec/db-live-monitor/assets/121028433/c51613a4-6497-4dbc-97a2-87b786c14d82)

As I said, small thing but it kinda set me off. If it is not fixable, I am sorry if I wasted your time.
Keep it up and good luck.

EDIT: I hope it helps to mention, that I used the link in the readme to go to the page...

**Comment by crwntec** [comment]
Hey Teconia 
I've noticed it myself and it's definitely an easy one to fix. I've updated the roadmap and will fix it as soon as I get back to the project.

Btw I've never thought that anybody would see this repo so thanks for your interest in the project 😃
